default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USER") %>
  password: <%= ENV.fetch("DB_PASSWORD") %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: <%= ENV.fetch("DB_PORT", "5432") %>

development:
  <<: *default
  database: scilents_development

test:
  <<: *default
  database: scilents_test

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *primary_production
    database: medipubs_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: medipubs_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: medipubs_production_cable
    migrations_paths: db/cable_migrate
